###
POST http://localhost:8080/api/v1/points/earn
Content-Type: application/json

{
  "userId": 5000,
  "amount": 1000,
  "isManual": false,
  "refId" : "ORD_00001"
}

### 관리자적립
POST http://localhost:8080/api/v1/points/earn
Content-Type: application/json

{
  "userId": 5001,
  "amount": 1000,
  "isManual": true,
  "refId" : "ORD_00002"
}

### 적립취소
POST http://localhost:8080/api/v1/points/earn/cancel
Content-Type: application/json

{
  "userId": 5001,
  "pointItemId": 788082542670602298,
  "reason": "테스트"
}

#######################
POST http://localhost:8080/api/v1/points/use
Content-Type: application/json

{
"userId": 5001,
"amount": 1000,
"orderId": "test3"
}

#######################
POST http://localhost:8080/api/v1/points/use/cancel
Content-Type: application/json

{
  "userId": 5000,
  "cancelAmount": 500,
  "orderId": "test3"
}
